export const ROLES = {
  WORKER: "WORKER",
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
};
export const PERMISSIONS = {
  PROJECT_READ: "PROJECT_READ",
  PROJECT_WRITE: "PROJECT_WRITE",
  PROJECT_DELETE: "PROJECT_DELETE",
  TASK_READ: "TASK_READ",
  TASK_WRITE: "TASK_WRITE",
  TASK_DELETE: "TASK_DELETE",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  ORDER_MANAGEMENT: "ORDER_MANAGEMENT",
  ORDER_DASHBOARD: "ORDER_DASHBOARD",
  PROJECT_DASHBOARD: "PROJECT_DASHBOARD",
};
